[package]
name = "single_byte_xor"
version = "0.1.0"
authors = ["owen"]
edition = "2018"

[dependencies]
converter = {path = "../../tools/converter"}
pattern_matcher = {path = "../../tools/pattern_matcher"}