[package]
name = "detect_single_byte_XOR"
version = "0.1.0"
authors = ["owen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dictionary_trie = {path = "../../tools/dictionary_trie"}
file_reader = {path = "../../tools/file_reader"}
pattern_matcher = {path = "../../tools/pattern_matcher"}
toolkit = {path = "../../tools/toolkit"}