directory="../toolkit/resources/"
mieliestrok_work_list="MieliestrokWordList"
most_common_digraphs="MostCommonDigraphsEnglish"
most_common_doubles="MostCommonDoublesEnglish"
most_common_four_letter_words="MostCommonWordsEnglish"
most_common_initial_letter="MostCommonInitialLetterEnglish"
most_common_last_letter="MostCommonLastLetterEnglish"
most_common_letters="MostCommonLettersEnglish"
most_common_one_letter_words="MostCommonOneLetterWordsEnglish"
most_common_three_letter_words="MostCommonThreeLetterWordsEnglish"
most_common_trigraphs="MostCommonTrigraphsEnglish"
most_common_two_letter_words="MostCommonTwoLetterWordsEnglish"
